/**
 * The return digest (PRD 3.6, 7.1).
 *
 * "On return after an idle period over 30 minutes, Picasso composes a digest
 * card: what moved, which detectors fired, which theses on the canvas are now
 * contradicted by data. The digest is generated by a mid-tier open-weight
 * model reading structured detector output, not raw prose, so it is cheap and
 * deterministic in shape."
 *
 * And from the walkthrough: "The digest card, generated by the 8B model from
 * structured detector output at 4:32pm, states in four lines what fired and
 * which two thesis nodes are now in `contradicted` status. Cost of that digest:
 * about 0.02 cents."
 *
 * **"Deterministic in shape" is the requirement, and it constrains where the
 * model is allowed to stand.** If the model chose what to mention, two
 * identical mornings would produce two different cards and the analyst would
 * have to read the whole thing to find out whether anything changed. So the
 * selection, the ranking, the numbers and the line count are computed here;
 * the model's only job is to write the sentence for a line whose content is
 * already decided. That is also why it is cheap: the payload is a few hundred
 * tokens of structured detector output, not a session's worth of prose.
 *
 * `compose` therefore produces the whole card without a model. A prose writer
 * can be supplied and it can only rewrite lines, never add, drop or reorder
 * them.
 */

import type { HypothesisStatus } from '@picasso/canvas-hypothesis';

/** PRD 3.6's threshold. */
export const IDLE_MS = 30 * 60 * 1000;

/** "states in four lines". The card is a glance, not a report. */
export const MAX_LINES = 4;

export function shouldDigest(idleMs: number): boolean {
  return idleMs > IDLE_MS;
}

export type DetectorFamily = 'robust_z' | 'bocpd' | 'stl_residual';

export interface DetectorEvent {
  nodeId: string;
  label: string;
  family: DetectorFamily;
  /** Standardized magnitude, so families rank against each other. */
  severity: number;
  at: number;
}

export interface Move {
  nodeId: string;
  label: string;
  /** Percent change over the idle window. */
  pct: number;
  /** In units of the node's own rolling dispersion. */
  z: number;
}

export interface ThesisChange {
  nodeId: string;
  claim: string;
  from: HypothesisStatus;
  to: HypothesisStatus;
}

export interface StaleNode {
  nodeId: string;
  label: string;
  reason: string;
}

export interface DigestInput {
  /** Start of the idle window. */
  since: number;
  now: number;
  moves: readonly Move[];
  events: readonly DetectorEvent[];
  thesisChanges: readonly ThesisChange[];
  stale: readonly StaleNode[];
}

export type DigestSection = 'thesis' | 'detector' | 'move' | 'stale';

export interface DigestLine {
  section: DigestSection;
  /** The sentence. Deterministic; a prose writer may only restate it. */
  text: string;
  nodeIds: string[];
  /** What put this line above the ones that were cut. */
  rank: number;
}

export interface Digest {
  at: number;
  idleMs: number;
  lines: DigestLine[];
  /** Everything that qualified, including what did not fit. */
  considered: number;
  /** The structured payload a model would be handed, as it would be serialized. */
  payload: string;
}

/**
 * Rank, then cut.
 *
 * A thesis moving to `contradicted` outranks any price move, because it is the
 * only item on the card that says the analyst's own stated belief is now wrong
 * — the walkthrough's card leads with two of them. Detector fires come next
 * ranked by severity, then raw moves by how many dispersions they travelled,
 * then stale compute nodes. Within a section the order is by magnitude and
 * then by node id, so a tie does not reshuffle between two runs.
 */
const SECTION_RANK: Record<DigestSection, number> = {
  thesis: 3000,
  detector: 2000,
  move: 1000,
  stale: 0,
};

export function compose(input: DigestInput, writer?: (line: DigestLine) => string): Digest {
  const candidates: DigestLine[] = [];

  const contradicted = input.thesisChanges.filter((c) => c.to === 'contradicted');
  if (contradicted.length > 0) {
    candidates.push({
      section: 'thesis',
      text:
        contradicted.length === 1
          ? `1 thesis is now contradicted: ${contradicted[0]?.claim}`
          : `${contradicted.length} theses are now contradicted: ${contradicted
              .map((c) => c.claim)
              .join('; ')}`,
      nodeIds: contradicted.map((c) => c.nodeId),
      rank: SECTION_RANK.thesis + contradicted.length,
    });
  }

  const byFamily = new Map<DetectorFamily, DetectorEvent[]>();
  for (const event of input.events) {
    byFamily.set(event.family, [...(byFamily.get(event.family) ?? []), event]);
  }
  for (const [family, events] of [...byFamily.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    const worst = [...events].sort((a, b) => b.severity - a.severity || a.nodeId.localeCompare(b.nodeId));
    const lead = worst[0];
    if (!lead) continue;
    candidates.push({
      section: 'detector',
      text:
        events.length === 1
          ? `${FAMILY_NAME[family]} fired on ${lead.label} at severity ${lead.severity.toFixed(1)}`
          : `${FAMILY_NAME[family]} fired ${events.length} times, worst on ${lead.label} at severity ${lead.severity.toFixed(1)}`,
      nodeIds: worst.map((e) => e.nodeId),
      rank: SECTION_RANK.detector + lead.severity,
    });
  }

  const moves = [...input.moves].sort(
    (a, b) => Math.abs(b.z) - Math.abs(a.z) || a.nodeId.localeCompare(b.nodeId),
  );
  const lead = moves[0];
  if (lead) {
    const rest = moves.slice(1, 3);
    const tail = rest.length > 0 ? `, then ${rest.map((m) => `${m.label} ${signed(m.pct)}`).join(' and ')}` : '';
    candidates.push({
      section: 'move',
      text: `${lead.label} moved ${signed(lead.pct)} (${lead.z.toFixed(1)} sigma)${tail}`,
      nodeIds: moves.slice(0, 3).map((m) => m.nodeId),
      rank: SECTION_RANK.move + Math.abs(lead.z),
    });
  }

  if (input.stale.length > 0) {
    const first = input.stale[0];
    candidates.push({
      section: 'stale',
      text:
        input.stale.length === 1 && first
          ? `${first.label} is stale: ${first.reason}`
          : `${input.stale.length} nodes are stale, including ${first?.label} (${first?.reason})`,
      nodeIds: input.stale.map((s) => s.nodeId),
      rank: SECTION_RANK.stale + input.stale.length,
    });
  }

  const ranked = [...candidates].sort((a, b) => b.rank - a.rank || a.section.localeCompare(b.section));
  const kept = ranked.slice(0, MAX_LINES);
  const lines = writer
    ? kept.map((line) => ({ ...line, text: writer(line) }))
    : kept;

  return {
    at: input.now,
    idleMs: input.now - input.since,
    lines,
    considered: candidates.length,
    payload: serialize(input),
  };
}

const FAMILY_NAME: Record<DetectorFamily, string> = {
  robust_z: 'robust z',
  bocpd: 'changepoint',
  stl_residual: 'seasonal residual',
};

function signed(pct: number): string {
  return `${pct >= 0 ? '+' : ''}${pct.toFixed(1)}%`;
}

/**
 * The payload the model reads.
 *
 * Structured detector output, abbreviated to the fields a sentence needs.
 * Nothing here is prose, and nothing here is a series: the whole reason the
 * digest costs a fraction of a cent is that the expensive material never
 * reaches the prompt.
 */
function serialize(input: DigestInput): string {
  return JSON.stringify({
    window: [input.since, input.now],
    moves: input.moves.map((m) => [m.label, round(m.pct, 1), round(m.z, 1)]),
    events: input.events.map((e) => [e.label, e.family, round(e.severity, 1)]),
    theses: input.thesisChanges.map((c) => [c.claim, c.from, c.to]),
    stale: input.stale.map((s) => [s.label, s.reason]),
  });
}

function round(value: number, places: number): number {
  const scale = 10 ** places;
  return Math.round(value * scale) / scale;
}

/**
 * What the digest costs on a given model.
 *
 * Four characters to the token is the usual English approximation and it is
 * pessimistic on a JSON payload of short labels and numbers, which tokenizes
 * worse than prose. Output is bounded by the card: four lines of one sentence.
 */
export function estimateCostCents(digest: Digest, centsPerKiloToken: number): number {
  const inputTokens = Math.ceil(digest.payload.length / 4) + PROMPT_TOKENS;
  const outputTokens = MAX_LINES * 32;
  return ((inputTokens + outputTokens) / 1000) * centsPerKiloToken;
}

/** The fixed instruction that wraps the payload. Measured once, not guessed at. */
export const PROMPT_TOKENS = 180;
